heat_template_version: 2014-10-16

description: >
  OpenShift Etcd nodes

parameters:

  volume_size:
    type: number
    description: Size of cinder volume use for node boot volume.
    default: 20

  # What version of OpenShift Enterprise to install
  # This value is used to select the RPM repo for the OSE release to install
  ose_version:
    type: string
    description: >
      The version of OpenShift Enterprise to deploy

  key_name:
    description: >
      A pre-submitted SSH key to access the VM hosts
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    description: >
      Select a base image to use for the etcd servers
    type: string

  flavor:
    description: >
      Define the hardware characteristics for the VMs: CPU, Memory, base disk
    type: string
    constraints:
    - custom_constraint: nova.flavor

  dns_ip:
    description: IP address of the internal DNS server
    type: string

  rhn_username:
    description: >
      A valid user with entitlements to RHEL and OpenShift software repos
    type: string

  rhn_password:
    description: >
      The password for the RHN user
    type: string
    hidden: true

  # Red Hat satellite subscription parameters
  sat6_hostname:
    type: string
    description: >
      The hostname of the Satellite 6 server which will provide software updates
    default: ''

  sat6_organization:
    type: string
    description: >
      An organization string provided by Sat6 to group subscriptions
    default: ''

  sat6_activationkey:
    type: string
    description: >
      An activation key string provided by Sat6 to enable subscriptions
    default: ''

  rhn_pool:
    description: >
      A subscription pool containing the RHEL and OpenShift software repos
      OPTIONAL
    type: string
    hidden: true

  extra_rhn_pools:
    type: comma_delimited_list
    description: List of rhn pools which will be installed on each node.
    default: ''

  hostname:
    description: >
      A string to identify etcd hostnames.
    type: string

  domain_name:
    description: >
      The DNS domain suffix. All VMs will be placed in this domain
    type: string

  ansible_public_key:
    description: >
      The SSH public key that Ansible will use to access etcd hosts
      This will be placed on each VM host in /root/.ssh/authorized_keys
    type: string

  ssh_user:
    description: >
      The user for SSH access to the VM hosts
    type: string

  timeout:
    description: Time to wait until the etcd setup is ready.
    type: number
    default: 10800

  bastion_node:
    description: >
      The hostname of the bastion node in the deployment
    type: string
    default: ''

  fixed_network:
    description: >
      The name or ID of the admin and public network
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    description: >
      The name or ID of the admin and public IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  etcd_server_group:
    description: >
      ID of a server group containing all of the etcd hosts
    type: string

  etcd_security_group:
    description: >
      ID of the network access policies for the OpenShift etcd hosts
    type: string

  skip_dns:
    type: boolean

  system_update:
    type: boolean

  extra_repository_urls:
    type: comma_delimited_list
    description: List of repository URLs which will be installed on each node.
    default: ''

resources:

  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: volume_size}
      snapshot_id: {get_param: image}

  # Create a network connection on the internal communications network
  port:
    type: OS::Neutron::Port
    properties:
      security_groups:
      - {get_param: etcd_security_group}
      network: {get_param: fixed_network}
      fixed_ips:
      - subnet: {get_param: fixed_subnet}
      replacement_policy: AUTO

  # Create the VM instance to host the etcd service
  host:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: "HOST.DOMAIN"
          params:
            HOST: {get_param: hostname}
            DOMAIN: {get_param: domain_name}
      admin_user: {get_param: ssh_user}
      #image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: port}
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: init}
      scheduler_hints:
        group: {get_param: etcd_server_group}
      block_device_mapping: [{device_name: "vda", volume_id: {get_resource: cinder_volume}, delete_on_termination : "true" }]

  # Compose configuration data into a single structure
  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: set_hostname}
      - config: {get_resource: included_files}
      - config: {get_resource: rhn_register}
      - config: {get_resource: set_extra_repos}
      - config: {get_resource: host_update}
      - config: {get_resource: etcd_boot}

  # Compose the short hostname and fully qualified domain name for the new host
  set_hostname:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        disable_root: false
        hostname: {get_param: hostname}
        fqdn:
          str_replace:
            template: "HOST.DOMAIN"
            params:
              HOST: {get_param: hostname}
              DOMAIN: {get_param: domain_name}

  # Compile a set of standard configuration files to provide identity and access
  included_files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /usr/local/share/openshift-on-openstack/common_functions.sh
          permissions: 0755
          content:
            str_replace:
              params:
                $WC_NOTIFY: { get_attr: ['wait_handle', 'curl_cli'] }
              template: {get_file: fragments/common_functions.sh}
        - path: /usr/local/share/openshift-on-openstack/common_openshift_functions.sh
          permissions: 0755
          content: {get_file: fragments/common_openshift_functions.sh}
        - path: /usr/local/bin/retry
          permissions: 0755
          content: {get_file: fragments/retry.sh}
        ssh_authorized_keys:
        - {get_param: ansible_public_key}

  # Attach to a source of software updates for RHEL
  rhn_register:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $OSE_VERSION: {get_param: ose_version}
            $RHN_USERNAME: {get_param: rhn_username}
            $RHN_PASSWORD: {get_param: rhn_password}
            $SAT6_HOSTNAME: {get_param: sat6_hostname}
            $SAT6_ORGANIZATION: {get_param: sat6_organization}
            $SAT6_ACTIVATIONKEY: {get_param: sat6_activationkey}
            $POOL_ID: {get_param: rhn_pool}
            $EXTRA_POOL_IDS:
              list_join:
                - " --pool="
                - {get_param: extra_rhn_pools}
          template: {get_file: fragments/rhn-register.sh}

  # Enable any extra repositories
  set_extra_repos:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $REPOLIST:
              list_join:
                - " "
                - {get_param: extra_repository_urls}
          template: {get_file: fragments/set-extra-repos.sh}

  # Insure that the host software is current
  host_update:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $SYSTEM_UPDATE: {get_param: system_update}
          template: {get_file: fragments/host-update.sh}

  # Prepare the host to run Docker and Ansible for OpenShift install and config
  etcd_boot:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $DNS_IP: {get_param: dns_ip}
            $SKIP_DNS: {get_param: skip_dns}
          template: {get_file: fragments/etcd-boot.sh}

  # Add a node's IP/Name mapping to DNS
  node_add:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: node_etc_host
      - name: node_hostname
      - name: node_type
      outputs:
      - name: result
      config:
        str_replace:
          params:
            $SKIP_DNS: {get_param: skip_dns}
          template: {get_file: fragments/bastion-node-add.sh}

  # Add the hostname and address of the bastion host to the etcd host
  deployment_bastion_node_add:
    depends_on: wait_condition
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: node_add
      server:
        get_param: bastion_node
      input_values:
        node_type: etcd
        node_hostname:
          str_replace:
            template: "HOST.DOMAIN"
            params:
              HOST: {get_param: hostname}
              DOMAIN: {get_param: domain_name}
        node_etc_host:
          str_replace:
              template: "IP HOST.DOMAIN HOST #openshift"
              params:
                IP: {get_attr: [port, fixed_ips, 0, ip_address]}
                HOST: {get_param: hostname}
                DOMAIN: {get_param: domain_name}

  node_cleanup:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
      - name: node_name
      - name: node_type
      - name: ssh_user
        default: {get_param: ssh_user}
      outputs:
      - name: result
      config:
        str_replace:
          params:
            $SKIP_DNS: {get_param: skip_dns}
          template: {get_file: fragments/bastion-node-cleanup.sh}

  # activation hook for removing the node from DNS and from the Kubernetes
  # cluster
  deployment_bastion_node_cleanup:
    depends_on: [host, wait_condition]
    type: OS::Heat::SoftwareDeployment
    properties:
      actions: ['DELETE']
      input_values:
        node_type: etcd
        node_name:
          str_replace:
            template: "HOST.DOMAIN"
            params:
              HOST: {get_param: hostname}
              DOMAIN: {get_param: domain_name}
      config:
        get_resource: node_cleanup
      server:
        get_param: bastion_node

  # Wait for etcd_boot (cloud-init) to complete or time out
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      timeout: {get_param: timeout}

  # This provides a curl CLI string to the cloud-init script which is queried
  # with a status at the end of of the cloud-init process
  wait_handle:
    type: OS::Heat::WaitConditionHandle

outputs:
  wc_data:
    description: Syncronization data
    value: { get_attr: ['wait_condition', 'data'] }
  hostname:
    description: The actual short name for the host
    value: {get_param: hostname}
  host:
    description: A reference to the etcd host identifier
    value: {get_resource: host}
