heat_template_version: 2014-10-16

description: >
  A template which provides a creates a loadbalancer using neutron's LBaaS.

parameters:

  # What version of OpenShift Container Platform to install
  # This value is used to select the RPM repo for the OCP release to install
  ocp_version:
    type: string
    description: >
      The version of OpenShift Container Platform to deploy

  key_name:
    description: >
      A pre-submitted SSH key to access the VM hosts
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    default: ''

  flavor:
    description: >
      Define the hardware characteristics for the VMs: CPU, Memory, base disk
    type: string
    constraints:
    - custom_constraint: nova.flavor

  timezone:
    description: >
      The server timezone
    type: string
    default: 'Etc/UTC'

  hostname:
    description: >
      The load balancer hostname portion of the FQDN
    type: string

  stack_name:
    description: Top level stack name.
    type: string

  domain_name:
    description: >
      All VMs will be placed in this domain
    type: string

  app_subdomain:
    type: string

  rhn_username:
    description: >
      A valid user with entitlements to RHEL and OpenShift software repos
    type: string

  rhn_password:
    description: >
      The password for the RHN user
    type: string
    hidden: true

  # Red Hat satellite subscription parameters
  sat6_hostname:
    type: string
    description: >
      The hostname of the Satellite 6 server which will provide software updates
    default: ''

  sat6_organization:
    type: string
    description: >
      An organization string provided by Sat6 to group subscriptions
    default: ''

  sat6_activationkey:
    type: string
    description: >
      An activation key string provided by Sat6 to enable subscriptions

  rhn_pool:
    description: >
      A subscription pool containing the RHEL and OpenShift software repos
      OPTIONAL
    type: string
    hidden: true

  extra_rhn_pools:
    type: comma_delimited_list
    description: List of rhn pools which will be installed on each node.
    default: ''

  ssh_user:
    description: >
      The user for SSH access to the VM hosts
    type: string

  ansible_public_key:
    description: >
      The SSH public key that Ansible will use to access master and node hosts
      This will be placed on each VM host in /root/.ssh/authorized_keys
    type: string

  fixed_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  members:
    type: comma_delimited_list

  master_hostname:
    type: string

  floatingip_id:
    type: string

  floatingip:
    type: string

  fixed_network:
    description: >
      The name or ID of the internal network
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    description: >
      The name or ID of the internal IPv4 space
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  extra_repository_urls:
    type: comma_delimited_list
    description: List of repository URLs which will be installed on each node.
    default: ''

  extra_docker_repository_urls:
    type: comma_delimited_list
    description: List of docker repository URLs which will be installed on each node, if a repo is insecure use '#insecure' suffix.
    default: ''

  # Delay openshift installation until the master is ready to accept
  timeout:
    description: Time to wait until the master setup is ready.
    type: number
    default: 4000

  hostname:
    description: >
      The load balancer hostname portion of the FQDN
    type: string
    constraints:
    - allowed_pattern: '[a-z0-9\-\.]*'
      description: Hostname must contain only characters [a-z0-9\-\.].

  stack_name:
    type: string
    default: ''

  bastion_node:
    type: string
    description: >
      The name or ID of the bastion instance.
    default: ''

  dns_servers:
    type: comma_delimited_list
    description: address of dns nameservers reachable in your environment

  dns_update_key:
    type: string
    hidden: true

  ca_cert:
    type: string
    description: Certificate Authority Certificate to be added to trust chain

outputs:
  console_url:
    description: URL of the OpenShift web console
    value:
      str_replace:
        template: "https://%hostname%.%domainname%:8443/console/"
        params:
          '%hostname%': {get_param: master_hostname}
          '%domainname%': {get_param: domain_name}

  api_url:
    description: URL entrypoint to the OpenShift API
    value:
      str_replace:
        template: "https://%hostname%.%domainname%:8443/"
        params:
          '%hostname%': {get_param: master_hostname}
          '%domainname%': {get_param: domain_name}

  hostname:
    description: Loadbalancer hostname
    value:
      str_replace:
        template: "%stack_name%-%hostname%.%domainname%"
        params:
          '%stack_name%': {get_param: stack_name}
          '%hostname%': {get_param: hostname}
          '%domainname%': {get_param: domain_name}
