heat_template_version: 2016-10-14

description: >
  A template which creates a cinder volume used by openshift registry,
  this volume is deleted with stack.

parameters:
  volume_id:
    description: >
      An existing cinder volume ID
    type: string
    default: ''

  volume_size:
    description: >
      Size of the Openshift registry persistent volume
    type: number


outputs:
  volume_id:
    description: cinder volume id
    value: {get_param: volume_id}
