#!/bin/bash

set -eu
set -x
set -o pipefail

if [ -n "$LDAP_HOSTNAME" -a -n "$LDAP_IP" ]; then
    echo "$LDAP_IP $LDAP_HOSTNAME" >> /etc/hosts
fi

if [ -n "$LB_HOSTNAME" -a -n "$LB_IP" ]; then
    echo "$LB_IP $LB_HOSTNAME $LB_HOSTNAME.$LB_DOMAIN" >> /etc/hosts
fi
