heat_template_version: 2016-10-14

parameters:

  # What version of OpenStack Platform to install
  # This value is used to select the RPM repo for the OSP release to install
  osp_version:
    type: string
    default: "10"
    description: >
      The version of OpenStack Platform to use to collect data

resources:

  install_config_agent_yum:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config:
        str_replace:
          params:
            $OSP_VERSION: {get_param: osp_version}
          template: {get_file: fragments/install_config_agent_yum.sh}

  configure_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: {get_file: fragments/configure_config_agent.sh}

  start_config_agent:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: {get_file: fragments/start_config_agent.sh}

  install_config_agent:
    type: "OS::Heat::MultipartMime"
    properties:
      parts:
      - config: {get_resource: install_config_agent_yum}
      - config: {get_resource: configure_config_agent}
      - config: {get_resource: start_config_agent}

outputs:
  config:
    value: {get_resource: install_config_agent}
